apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-p
  labels:
    app: ${POOL_NAME}
spec:
  replicas: ${VLLM_REPLICA_COUNT_P}
  selector:
    matchLabels:
      app: ${POOL_NAME}
  template:
    metadata:
      labels:
        app: ${POOL_NAME}
        llm-d.ai/role: prefill
    spec:
      containers:
      - name: vllm
        image: ghcr.io/llm-d/llm-d-inference-sim:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8000"
        - "--model=${MODEL_NAME}"
        - "--lora=\"l1,l2,l3\""
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-sim-d
  labels:
    app: ${POOL_NAME}
spec:
  replicas: ${VLLM_REPLICA_COUNT_D}
  selector:
    matchLabels:
      app: ${POOL_NAME}
  template:
    metadata:
      labels:
        app: ${POOL_NAME}
        llm-d.ai/role: decode
    spec:
      initContainers:
      - name: routing-sidecar
        image: ghcr.io/llm-d/llm-d-routing-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8000"
        - "--vllm-port=8200"
        - "--connector=lmcache"
        ports:
        - containerPort: 8000
          protocol: TCP
        restartPolicy: Always
      containers:
      - name: vllm
        image: ghcr.io/llm-d/llm-d-inference-sim:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8200"
        - "--model=${MODEL_NAME}"
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        env:
        - name: PORT
          value: "8200"
