apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MODEL_NAME_SAFE}-vllm-sim
  labels:
    app: ${POOL_NAME}
spec:
  replicas: ${VLLM_REPLICA_COUNT}
  selector:
    matchLabels:
      app: ${POOL_NAME}
  template:
    metadata:
      labels:
        app: ${POOL_NAME}
    spec:
      containers:
      - name: vllm
        image: ghcr.io/llm-d/llm-d-inference-sim:latest
        imagePullPolicy: IfNotPresent
        args:
        - '--port=8000'
        - '--model=${MODEL_NAME}'
        - '--lora-modules'
        - '{"name":"l1"}'
        - '{"name":"l2"}'
        - '{"name":"l3"}'
        - '--time-to-first-token=30000'
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
